###
POST http://localhost:5000/api/auth/signup
Content-Type: application/json

{
  "username": "TestUser3",
  "password": "testpass3"
}

###
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "username": "TestUser2",
  "password": "testpass2"
}

###
POST http://localhost:5000/api/auth/logout
Content-Type: application/json