###
POST http://localhost:5000/api/auth/signup
Content-Type: application/json

{
  "username": "TestUser3",
  "password": "testpass3"
}

###
POST http://localhost:5000/login
Content-Type: application/json

{
  "username": "TestUser2",
  "password": "testpass2"
}

###
POST http://localhost:5000/api/auth/logout
Content-Type: application/json

###
POST http://localhost:5000/add
Content-Type: application/json

{
  "name": "Bet Lost",
  "originalUrl": "https://www.youtube.com/watch?v=IshbWXpDfD4&t=329s"
}

###
DELETE http://localhost:5000/6737087a9190c9a1b5798c23

###
GET http://localhost:5000/YtwE4KO4

###
GET http://localhost:5000/analytics/ahUY